version: "3.6"
services:
  redis-master1: 
     image: redis:6.0 # 基础镜像
     container_name: redis-master1 # 容器服务名
     working_dir: /config # 工作目录
     environment: # 环境变量
       - PORT=6392 # 跟 config/nodes-6391.conf 里的配置一样的端口
     ports: # 映射端口，对外提供服务
       - "6392:6392" # redis 的服务端口
       - "16392:16392" # redis 集群监控端口
     stdin_open: true # 标准输入打开
     networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.2
     tty: true
     privileged: true # 拥有容器内命令执行的权限
     volumes: ["/Users/weichangming/install/redis-config:/config"] # 映射数据卷，配置目录
     entrypoint: # 设置服务默认的启动程序
       - /bin/bash
       - redis.sh
  redis-master2:
       image: redis:6.0
       working_dir: /config
       container_name: redis-master2
       environment:
              - PORT=6393
       networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.3
       ports:
         - "6393:6393"
         - "16393:16393"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/Users/weichangming/install/redis-config:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-master3:
       image: redis:6.0
       container_name: redis-master3
       working_dir: /config
       environment:
              - PORT=6394
       networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.4
       ports:
         - "6394:6394"
         - "16394:16394"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/Users/weichangming/install/redis-config:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave1:
       image: redis:6.0
       container_name: redis-slave1
       working_dir: /config
       environment:
            - PORT=6395
       networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.5
       ports:
         - "6395:6395"
         - "16395:16395"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/Users/weichangming/install/redis-config:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve2:
       image: redis:6.0
       working_dir: /config
       container_name: redis-salve2
       environment:
             - PORT=6396
       ports:
         - "6396:6396"
         - "16396:16396"
       stdin_open: true
       networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.6
       tty: true
       privileged: true
       volumes: ["/Users/weichangming/install/redis-config:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve3:
       image: redis:6.0
       container_name: redis-slave3
       working_dir: /config
       environment:
          - PORT=6397
       ports:
         - "6397:6397"
         - "16397:16397"
       stdin_open: true
       networks: # docker 网络设置
        redis-network:
            ipv4_address: 172.50.0.7
       tty: true
       privileged: true
       volumes: ["/Users/weichangming/install/redis-config:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
networks:
  redis-network:
     driver: bridge # 创建一个docker 的桥接网络
     ipam:
       driver: default
       config:
          -
           subnet: 172.50.0.0/16